#spring.application.name=ms-gateway-server
spring:
  application:
    name: ms-gateway-server
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:password@localhost:7070

