server:
  #  port: 8097
  port: ${PORT:${SERVER_PORT:0}}

spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    # CONEXION A BASE DE DATOS
  datasource:
    datasource:
      url: jdbc:mysql://localhost:3306/seguridad
      username: root
      password: ""
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:

    defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:

    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}