server:
  port: 8091

spring:
  application:
    name: ms-estudiante-service

  # CONEXIÓN A BASE DE DATOS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgredb
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html  # Cambié esta ruta

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost