#spring.application.name=ms-microservicio2
spring:
  application:
    name: ms-microservicio2
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:password@localhost:7070
